version: 2.1

commands:
  all-tests:
    description: Roda todos os testes do projeto (unitários e integração)
    steps:
      - run: npm t
  coverage-report:
    description: Gera o relatório de coverage
    steps:
      - run: npm run test:coverage-report
  format-check:
    description: Verifica formatação do código
    steps:
      - run: npm run fmt:check
  install-deps:
    description: Instala dependências do projeto
    steps:
      - run: npm install 
  upload-coverage:
    description: Faz o envio do relatório de cobertura de testes para o Codecov
    steps:
      - run:
          command: bash <(curl -s https://codecov.io/bash)

jobs:
  build:
    parameters:
      image:
        default: node:lts
        description: Nome da imagem principal onde rodará o build
        type: string
      coverage:
        default: false
        description: Indica se o relatório de cobertura será gerado e enviado ao Codecov
        type: boolean
    docker:
      - image: <<parameters.image>>
        #auth:
          #username: $B2WADS_DOCKER_REGISTRY_USERNAME
          #password: $B2WADS_DOCKER_REGISTRY_PASSWORD
      #- image: mongo:3.6
      #- image: elasticsearch:5
      #- image: rabbitmq:3.6-alpine
      #- image: redis:5
    steps:
      - checkout
      - install-deps
      - format-check
      - all-tests
      - when:
          condition: <<parameters.coverage>>
          steps: 
            - coverage-report
            - upload-coverage

# O `context:` abaixo deve ser usado se você precisa
# de uma imagem privada. Nesse context devem estar cadastradas as envs:
# - B2WADS_DOCKER_REGISTRY_USERNAME
# - B2WADS_DOCKER_REGISTRY_PASSWORD
workflows:
  version: 2
  required-checks:
    jobs:
      - build:
          name: node-12_13_0
          context: docker-registry-auth
          image: node:12.13.0
  optional-checks:
    jobs:
      - build:
          name: node-lts
          context: docker-registry-auth
          coverage: false
      - build:
          name: node-latest
          context: docker-registry-auth
          coverage: false
