name: Build and Test

on:
  pull_request:
    branches:
      - master

jobs:
  node-lts:
    runs-on: ubuntu-latest
    container:
      image: node:lts-alpine
      env: 
        NODE_ENV: test
    steps:
      - uses: actions/checkout@v1
      - name: Install deps
        run: npm install
      - name: Roda todos os testes do projeto (unitários e integração)
        run: npm test
        
